<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PodcastBatchCleaner.CrossPlatform\**\*.cs" />
    <None Remove="PodcastBatchCleaner.CrossPlatform\**\*" />
    <Page Remove="PodcastBatchCleaner.CrossPlatform\**\*.axaml" />
  </ItemGroup>
</Project>
